2024-12-23 11:56:28,386 - root - ERROR - Timestamp: 2024-12-23 11:56:28
Exception Type: NoDetectionError
Context: 10분 접속 처리 중 오류 발생
Error Details: passwordScreen 화면이 20회 이상 탐지되지 않았습니다.
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 75, in ten_min_start
    if self.password_handler.handle_password_screen(screen, loaded_templates, password_list, self.screen_state):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\detection\password_handler.py", line 60, in handle_password_screen
    raise e  # 예외를 발생시켜 상위 코드로 전달
    ^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\detection\password_handler.py", line 31, in handle_password_screen
    raise NoDetectionError(f"passwordScreen 화면이 {self.MAX_DETECTION_ATTEMPTS}회 이상 탐지되지 않았습니다.")
src.utils.error_handler.NoDetectionError: passwordScreen 화면이 20회 이상 탐지되지 않았습니다.

--------------------------------------------------------------------------------

2024-12-23 14:10:20,566 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-13' coro=<DoService._wait_and_check_timer() running at C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\do_service.py:115> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2024-12-23 14:35:54,416 - root - ERROR - Timestamp: 2024-12-23 14:35:54
Exception Type: CantFindTenMinDataError
Context: {'server_id': 4524, 'deanak_id': 1}
Error Details: 10분접속 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------

