2024-12-19 11:24:01,921 - root - ERROR - Timestamp: 2024-12-19 11:24:01
Exception Type: TypeError
Context: 작업 실패
Error Details: RemoteDao.update_tasks_request() missing 1 required positional argument: 'request'
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 85, in ten_min_start
    await self.remote_pcs_dao.update_tasks_request(db, server_id, "waiting")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RemoteDao.update_tasks_request() missing 1 required positional argument: 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 98, in ten_min_start
    await self.remote_pcs_dao.update_tasks_request(db, server_id, "stopped")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RemoteDao.update_tasks_request() missing 1 required positional argument: 'request'

--------------------------------------------------------------------------------

2024-12-19 11:33:38,657 - root - ERROR - Timestamp: 2024-12-19 11:33:38
Exception Type: CantFindTenMinDataError
Context: {'server_id': 76864, 'deanak_id': 1}
Error Details: auto_ten_min 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------

2024-12-19 13:55:50,193 - root - ERROR - Timestamp: 2024-12-19 13:55:50
Exception Type: NoDetectionError
Context: 자동 대낙 처리 중 오류 발생
Error Details: team_select_screen 화면이 20회 이상 탐지되지 않았습니다.
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 75, in ten_min_start
    if self.ten_min_screen_handler.handle_ten_min_screen(screen, loaded_templates, self.screen_state):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\detection\ten_min_handler.py", line 42, in handle_ten_min_screen
    raise e
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\detection\ten_min_handler.py", line 30, in handle_ten_min_screen
    raise NoDetectionError(f"team_select_screen 화면이 {self.MAX_DETECTION_ATTEMPTS}회 이상 탐지되지 않았습니다.")
src.utils.error_handler.NoDetectionError: team_select_screen 화면이 20회 이상 탐지되지 않았습니다.

--------------------------------------------------------------------------------

2024-12-19 14:04:17,482 - root - ERROR - Timestamp: 2024-12-19 14:04:17
Exception Type: CantFindTenMinDataError
Context: {'server_id': 14752, 'deanak_id': 1}
Error Details: auto_ten_min 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------

2024-12-19 14:24:49,539 - root - ERROR - Timestamp: 2024-12-19 14:24:49
Exception Type: CantFindTenMinDataError
Context: {'server_id': 87324, 'deanak_id': 1}
Error Details: auto_ten_min 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------

2024-12-19 16:26:22,283 - root - ERROR - Timestamp: 2024-12-19 16:26:22
Exception Type: NoDetectionError
Context: 자동 대낙 처리 중 오류 발생
Error Details: passwordScreen 화면이 20회 이상 탐지되지 않았습니다.
Traceback:
Traceback (most recent call last):
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\auto_ten_min.py", line 69, in ten_min_start
    if self.password_handler.handle_password_screen(screen, loaded_templates, password_list, self.screen_state):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\detection\password_handler.py", line 60, in handle_password_screen
    raise e  # 예외를 발생시켜 상위 코드로 전달
    ^^^^^^^
  File "C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\detection\password_handler.py", line 31, in handle_password_screen
    raise NoDetectionError(f"passwordScreen 화면이 {self.MAX_DETECTION_ATTEMPTS}회 이상 탐지되지 않았습니다.")
src.utils.error_handler.NoDetectionError: passwordScreen 화면이 20회 이상 탐지되지 않았습니다.

--------------------------------------------------------------------------------

2024-12-19 16:26:30,147 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-13' coro=<DoService._wait_and_check_timer() running at C:\Users\gameins\Desktop\auto_deanak_program\ten_min\src\service\do_service.py:108> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2024-12-19 18:11:40,788 - root - ERROR - Timestamp: 2024-12-19 18:11:40
Exception Type: CantFindTenMinDataError
Context: {'server_id': 47979, 'deanak_id': 1}
Error Details: auto_ten_min 데이터를 찾을 수 없습니다.
Traceback:
NoneType: None

--------------------------------------------------------------------------------

